# Generated by Django 4.2.30 on 2026-08-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_status'),
        ('notes', '0003_alter_note_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='subjects.topic', verbose_name='Tópico'),
        ),
    ]
