# Generated by Django 4.2.30 on 2026-09-01 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0004_contest_main_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0003_subject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('alternativa_a', models.CharField(default='', max_length=500, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(default='', max_length=500, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(default='', max_length=500, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(default='', max_length=500, verbose_name='Alternativa D')),
                ('alternativa_correta', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Alternativa Correta')),
                ('explicacao', models.TextField(blank=True, verbose_name='Explicação')),
                ('dificuldade', models.PositiveSmallIntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], default=3, verbose_name='Dificuldade')),
                ('banca', models.CharField(blank=True, max_length=100, verbose_name='Banca')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('fonte', models.CharField(blank=True, max_length=200, verbose_name='Fonte')),
                ('status', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest', verbose_name='Concurso/Estudo')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='subjects.topic', verbose_name='Assunto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Simulated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('quantidade', models.PositiveIntegerField()),
                ('tempo_limite', models.PositiveIntegerField(help_text='Tempo em minutos')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxima_revisao', models.DateField()),
                ('intervalo', models.PositiveIntegerField(default=1)),
                ('vezes_revisado', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escolhida', models.CharField(max_length=1)),
                ('correta', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tempo_gasto', models.PositiveIntegerField(default=0, help_text='Tempo em segundos')),
                ('modo', models.CharField(choices=[('treino', 'Treino'), ('simulado', 'Simulado')], default='treino', max_length=20)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('desconhecido', 'Não conhecia o conteúdo'), ('esqueci', 'Esqueci'), ('confundi', 'Confundi conceitos'), ('interpretacao', 'Errei por interpretação'), ('desatencao', 'Desatenção'), ('chute', 'Chutei'), ('outro', 'Outro')], default='desconhecido', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('erro_consecutivo', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('resposta_escolhida', models.CharField(blank=True, max_length=1, null=True)),
                ('correta', models.BooleanField(blank=True, null=True)),
                ('tempo_gasto', models.PositiveIntegerField(default=0)),
                ('marcada', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('simulated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='questions.simulated')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('simulated', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='simulated',
            index=models.Index(fields=['user', 'status'], name='questions_s_user_id_ddea4b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionreview',
            index=models.Index(fields=['user', 'proxima_revisao'], name='questions_q_user_id_86aea6_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'question'], name='questions_q_user_id_d71862_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'correta'], name='questions_q_user_id_65235f_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['user', 'data'], name='questions_q_user_id_785fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'dificuldade'], name='questions_q_topic_i_530c54_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['user', 'created_at'], name='questions_q_user_id_1a6f46_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['banca', 'ano'], name='questions_q_banca_ede539_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', 'question'], name='questions_e_user_id_63ec5d_idx'),
        ),
    ]
