# Generated by Django 4.2.30 on 2026-08-23 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_subject_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('alternativa_a', models.CharField(default='', max_length=500, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(default='', max_length=500, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(default='', max_length=500, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(default='', max_length=500, verbose_name='Alternativa D')),
                ('alternativa_correta', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Alternativa Correta')),
                ('explicacao', models.TextField(blank=True, verbose_name='Explicação')),
                ('dificuldade', models.PositiveSmallIntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], default=3, verbose_name='Dificuldade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.topic', verbose_name='Assunto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-created_at'],
            },
        ),
    ]
