# Generated by Django 4.2.30 on 2026-09-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_add_new_models'),
    ]

    operations = [
    ]
