# Generated by Django 4.2.30 on 2026-09-29 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0004_contest_main_topic'),
        ('subjects', '0003_subject_status'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_a',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_b',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_c',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_correta',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_d',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='banca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='dificuldade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], default=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='explicacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='fonte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='tempo_gasto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionreview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='simulated',
            name='tempo_limite',
            field=models.PositiveIntegerField(),
        ),
    ]
