# Generated by Django 4.2.30 on 2026-10-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0003_subject_status'),
        ('contests', '0004_contest_main_topic'),
        ('questions', '0002_alter_question_options_alter_errorlog_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_a',
            field=models.CharField(default='', max_length=500, verbose_name='Alternativa A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_b',
            field=models.CharField(default='', max_length=500, verbose_name='Alternativa B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_c',
            field=models.CharField(default='', max_length=500, verbose_name='Alternativa C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_correta',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Alternativa Correta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='alternativa_d',
            field=models.CharField(default='', max_length=500, verbose_name='Alternativa D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='question',
            name='banca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banca'),
        ),
        migrations.AlterField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest', verbose_name='Concurso/Estudo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dificuldade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], default=3, verbose_name='Dificuldade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=models.TextField(verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explicacao',
            field=models.TextField(blank=True, verbose_name='Explicação'),
        ),
        migrations.AlterField(
            model_name='question',
            name='fonte',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='subjects.topic', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='tempo_gasto',
            field=models.PositiveIntegerField(default=0, help_text='Tempo em segundos'),
        ),
        migrations.AlterField(
            model_name='simulated',
            name='tempo_limite',
            field=models.PositiveIntegerField(help_text='Tempo em minutos'),
        ),
    ]
