# Generated by Django 4.2.30 on 2026-08-19 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_options_alter_topic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprogress',
            options={'verbose_name': 'Progresso diário', 'verbose_name_plural': 'Progressos diários'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'verbose_name': 'Sessão de estudo', 'verbose_name_plural': 'Sessões de estudo'},
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Acertos'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='flashcards_reviewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Flashcards revisados'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='hours_studied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas estudadas'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='questions_solved',
            field=models.PositiveIntegerField(default=0, verbose_name='Questões resolvidas'),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='daily', max_length=10, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_flashcards',
            field=models.PositiveIntegerField(default=20, verbose_name='Meta flashcards'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_hours',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Meta horas'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_questions',
            field=models.PositiveIntegerField(default=30, verbose_name='Meta questões'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Duração (min)'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='start_time',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='subjects.topic', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
