# Generated by Django 4.2.30 on 2026-08-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_dailyprogress_options_alter_goal_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
