# Generated by Django 4.2.30 on 2026-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_delete_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='hours_studied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas estudadas'),
        ),
    ]
