# Generated by Django 4.2.30 on 2026-08-23 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0004_alter_dailyprogress_hours_studied'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], default=3)),
                ('studied_at', models.DateTimeField(auto_now_add=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_contents', to='subjects.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteúdo de estudo',
                'verbose_name_plural': 'Conteúdos de estudo',
                'ordering': ['next_review'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='daily', max_length=10, verbose_name='Período')),
                ('target_hours', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Meta horas')),
                ('target_questions', models.PositiveIntegerField(default=30, verbose_name='Meta questões')),
                ('target_flashcards', models.PositiveIntegerField(default=20, verbose_name='Meta flashcards')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de início')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
