# Generated by Django 4.2.30 on 2026-10-06 02:15
# Editado manualmente para marcar sessões históricas como FINISHED
# antes de aplicar a constraint única parcial.

from django.db import migrations, models


def mark_existing_sessions_finished(apps, schema_editor):
    """Sessões que existiam antes do campo `status` são histórico, não ativas."""
    StudySession = apps.get_model('study', 'StudySession')
    StudySession.objects.all().update(status='FINISHED')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_studycontent_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Sessão de estudo', 'verbose_name_plural': 'Sessões de estudo'},
        ),
        migrations.AddField(
            model_name='studysession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pausada em'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(
                choices=[('RUNNING', 'Em andamento'), ('PAUSED', 'Pausada'), ('FINISHED', 'Finalizada')],
                db_index=True,
                default='RUNNING',
                max_length=10,
                verbose_name='Status',
            ),
        ),
        migrations.AddField(
            model_name='studysession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Segundos pausados (acumulado)'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        # ⬇⬇⬇ ESSA É A CORREÇÃO ⬇⬇⬇
        migrations.RunPython(mark_existing_sessions_finished, noop_reverse),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'status'], name='study_study_user_id_1a259c_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-start_time'], name='study_study_user_id_649a6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['RUNNING', 'PAUSED'])),
                fields=('user',),
                name='unique_active_session_per_user',
            ),
        ),
    ]
