# Generated by Django 4.2.30 on 2026-10-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_studycontent_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Sessão de estudo', 'verbose_name_plural': 'Sessões de estudo'},
        ),
        migrations.AddField(
            model_name='studysession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pausada em'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Em andamento'), ('PAUSED', 'Pausada'), ('FINISHED', 'Finalizada')], db_index=True, default='RUNNING', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Segundos pausados (acumulado)'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'status'], name='study_study_user_id_1a259c_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-start_time'], name='study_study_user_id_649a6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RUNNING', 'PAUSED'])), fields=('user',), name='unique_active_session_per_user'),
        ),
    ]
