# Generated by Django 4.2.30 on 2026-08-19 13:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0003_subject_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('dificuldade', models.PositiveSmallIntegerField(default=1, verbose_name='Dificuldade (1-5)')),
                ('intervalo', models.PositiveIntegerField(default=1, verbose_name='Intervalo (dias)')),
                ('facilidade', models.FloatField(default=2.5, verbose_name='Facilidade')),
                ('proxima_revisao', models.DateField(default=datetime.date.today, verbose_name='Próxima revisão')),
                ('vezes_revisado', models.PositiveIntegerField(default=0, verbose_name='Vezes revisado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='subjects.topic', verbose_name='Tópico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['proxima_revisao'],
            },
        ),
    ]
