# Generated by Django 4.2.30 on 2026-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='dificuldade',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muito fácil'), (2, 'Fácil'), (3, 'Médio'), (4, 'Difícil'), (5, 'Muito difícil')], default=3, verbose_name='Nível de dificuldade'),
        ),
    ]
