# Generated by Django 4.2.30 on 2026-08-19 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planejando'), ('studying', 'Estudando'), ('review', 'Revisão'), ('intensive', 'Intensivo'), ('finished', 'Finalizado'), ('archived', 'Arquivado')], default='planning', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('goal_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('goal_questions', models.IntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'exam_date'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
