# Generated by Django 4.2.30 on 2026-08-19 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-priority', 'exam_date'], 'verbose_name': 'Concurso', 'verbose_name_plural': 'Concursos'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='board',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banca'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da prova'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='goal_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Meta de horas'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='goal_questions',
            field=models.IntegerField(default=0, verbose_name='Meta de questões'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('planning', 'Planejando'), ('studying', 'Estudando'), ('review', 'Revisão'), ('intensive', 'Intensivo'), ('finished', 'Finalizado'), ('archived', 'Arquivado')], default='planning', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
