# Generated by Django 4.2.30 on 2026-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contest_options_alter_contest_board_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-priority', 'exam_date'], 'verbose_name': 'Estudo', 'verbose_name_plural': 'Estudos'},
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='board',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banca/Instituição'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Prova/Meta'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista (opcional)'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='goal_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Meta de Horas'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='goal_questions',
            field=models.IntegerField(default=0, verbose_name='Meta de Questões'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Estudo'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instituição/Curso'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Objetivo'),
        ),
    ]
