# Generated by Django 4.2.30 on 2026-08-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_options_contest_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='main_topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tópico principal'),
        ),
    ]
