# Generated by Django 4.2.30 on 2026-08-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='contests.contest')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('contest', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', '⚪ Não iniciado'), ('studying', '🔵 Estudando'), ('studied', '🟡 Estudado'), ('review_pending', '🟠 Revisão pendente'), ('needs_reinforcement', '🔴 Precisa reforço'), ('mastered', '🟢 Dominado')], default='not_started', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='subjects.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='topics', to='notes.tag')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('subject', 'parent', 'name')},
            },
        ),
    ]
