# Generated by Django 4.2.30 on 2026-08-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contest_options_alter_contest_board_and_more'),
        ('notes', '0003_alter_note_options_alter_tag_options_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='contests.contest', verbose_name='Concurso'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='subjects.topic', verbose_name='Tópico pai'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('not_started', '⚪ Não iniciado'), ('studying', '🔵 Estudando'), ('studied', '🟡 Estudado'), ('review_pending', '🟠 Revisão pendente'), ('needs_reinforcement', '🔴 Precisa reforço'), ('mastered', '🟢 Dominado')], default='not_started', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.subject', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topics', to='notes.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
