# Generated by Django 4.2.30 on 2026-08-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('not_started', '⚪ Não iniciado'), ('studying', '🔵 Estudando'), ('studied', '🟡 Estudado'), ('review_pending', '🟠 Revisão pendente'), ('needs_reinforcement', '🔴 Precisa reforço'), ('mastered', '🟢 Dominado')], default='not_started', max_length=20, verbose_name='Status'),
        ),
    ]
