# Generated by Django 4.2.30 on 2026-08-23 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('estudo', '📚 Estudo'), ('resumo', '📝 Resumo'), ('revisao', '🔄 Revisão'), ('questoes', '❓ Questões'), ('descanso', '😴 Descanso')], max_length=20, verbose_name='Tipo de dia')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de estudo',
                'verbose_name_plural': 'Planos de estudo',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
