# Generated by Django 4.2.30 on 2026-08-23 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('activity', models.CharField(choices=[('study', '📚 Estudo'), ('review', '🔄 Revisão'), ('questions', '❓ Questões'), ('summary', '📝 Resumo'), ('rest', '😴 Descanso')], max_length=20, verbose_name='Atividade')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dia de estudo',
                'verbose_name_plural': 'Dias de estudo',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
