# Generated by Django 4.2.30 on 2026-08-23 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0003_alter_contest_options_contest_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('concurso', 'Preparação para concurso'), ('vestibular', 'Preparação para vestibular'), ('faculdade', 'Faculdade'), ('certificacao', 'Certificação'), ('habilidade', 'Aprender uma nova habilidade'), ('prova_especifica', 'Estudar para uma prova específica'), ('rotina', 'Criar uma rotina geral de estudos'), ('outro', 'Outro')], default='concurso', max_length=20)),
                ('objective_custom', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='intermediario', max_length=15)),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='alta', max_length=10)),
                ('max_subjects', models.PositiveSmallIntegerField(default=3, verbose_name='Quantidade de matérias')),
                ('available_days', models.JSONField(default=list)),
                ('available_hours_start', models.TimeField(default='19:00')),
                ('available_hours_end', models.TimeField(default='22:00')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('days_per_week', models.PositiveSmallIntegerField(default=5)),
                ('study_weekend', models.BooleanField(default=False)),
                ('target_hours_week', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('target_hours_month', models.DecimalField(decimal_places=2, default=60.0, max_digits=6)),
                ('sessions_per_week', models.PositiveSmallIntegerField(default=5)),
                ('daily_goal_hours', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('active_recall', models.BooleanField(default=True, verbose_name='Recuperação ativa')),
                ('spaced_repetition', models.BooleanField(default=True, verbose_name='Repetição espaçada')),
                ('practice_questions', models.BooleanField(default=True, verbose_name='Prática com questões')),
                ('flashcards_active', models.BooleanField(default=True, verbose_name='Flashcards')),
                ('interleaving', models.BooleanField(default=True, verbose_name='Intercalação')),
                ('active_review', models.BooleanField(default=True, verbose_name='Revisão ativa')),
                ('review_intervals', models.JSONField(default=[1, 3, 7, 14, 30])),
                ('review_intensity', models.PositiveSmallIntegerField(choices=[(1, 'Leve (menos revisões)'), (2, 'Moderado'), (3, 'Intenso (mais revisões)')], default=3)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_contests', models.ManyToManyField(blank=True, related_name='study_configs', to='contests.contest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Estudos',
                'verbose_name_plural': 'Configurações de Estudos',
            },
        ),
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('subject_name', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('study', 'Estudo'), ('review', 'Revisão'), ('questions', 'Questões'), ('flashcards', 'Flashcards'), ('rest', 'Descanso')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão Planejada',
                'verbose_name_plural': 'Sessões Planejadas',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
