# Generated by Django 4.2.30 on 2026-09-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_status'),
        ('study_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedsession',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='active_recall',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='active_review',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='available_hours_end',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='available_hours_start',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='flashcards_active',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='interleaving',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='practice_questions',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='review_intensity',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='review_intervals',
        ),
        migrations.RemoveField(
            model_name='studyconfig',
            name='spaced_repetition',
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='origin',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('skipped', 'Pulada'), ('rescheduled', 'Reagendada')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to='subjects.topic'),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='adaptation_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('assistida', 'Assistida'), ('automatica', 'Automática')], default='assistida', max_length=10),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='availability',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='diagnostic_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='diagnostic_level',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca estudei'), ('pouca_base', 'Tenho pouca base'), ('conheco', 'Conheço o conteúdo'), ('boa_base', 'Tenho boa base'), ('domino', 'Domino')], max_length=20),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='intensity',
            field=models.CharField(choices=[('leve', 'Leve'), ('equilibrada', 'Equilibrada'), ('intensa', 'Intensa'), ('maxima', 'Máxima')], default='equilibrada', max_length=20),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='max_hours_week',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='min_hours_week',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='preferred_methods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='rest_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='session_duration',
            field=models.PositiveSmallIntegerField(choices=[(15, '15 min'), (25, '25 min'), (40, '40 min'), (60, '60 min'), (90, '90 min')], default=40),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='strategy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='target_flashcards_week',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='studyconfig',
            name='target_questions_week',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='plannedsession',
            name='session_type',
            field=models.CharField(choices=[('study', 'Estudo'), ('review', 'Revisão'), ('questions', 'Questões'), ('flashcards', 'Flashcards'), ('simulated', 'Simulado'), ('rest', 'Descanso')], default='study', max_length=20),
        ),
        migrations.AlterField(
            model_name='studyconfig',
            name='max_subjects',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
